language: ruby
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database dsel_test;' -U postgres
  - cp .env.travis .env.test
dist: trusty
rvm:
  - 2.4.4
before_install:
  gem install bundler
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec
